### PR TITLE
Added ppx support for lwt.

### PR DESCRIPTION
**Pull request by rizo**
Not sure if you are interested in including this but I made a straightforward conversion to Lwt ppx extension. Everything seems to work, the test passes too.

### CODE REVIEW

**Comment by rgrinberg** [comment]
IMO it would be better to just drop the syntax extensions altogether here and make it compatible with old ocaml + ppx ocaml

**Comment by ivg** [comment]
I agree with @rgrinberg, we should just drop of any syntax extensions. That will make library more portable. As if I will merge this PR this will automatically make library unavailable for older OCaml versions, and, that is more important, to projects that already rely on camlp4

**Comment by ivg** [comment]
Thanks, @rizo for the proposal, it gave me a good kick for goodness (to drop syntax extensions). I've merged branch #4 without any syntax extensions.

**Comment by rizo** [comment]
Great! I just didn't want to have to use camlp4 :p

**Pull request closed without merging**
